name: Python package

on:
    pull_request:
        branches:
            - "main"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
          pip install .[test]

      - name: Run unit tests
        run: |
          python -m unittest discover tests/

      - name: Create documentation
        run: |
          pip install sphinx-autobuild
          sphinx-autobuild docs docs/_build/html
